#!/bin/bash
### BEGIN INIT INFO
# Provides:          cube-collector
# Required-Start:    networking
# Required-Stop:     networking
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Run cube collector as daemon
# Description:       Run cube collector as daemon
#                    https://github.com/lmammino/cube-daemons
### END INIT INFO

. /lib/lsb/init-functions

NAME="cube-collector"
NODE_PREFIX="%NODE_PREFIX%"
PIDFILE="/var/run/cube/collector.pid"
APP_DIR="/usr/bin"
APP_BIN="env"
NODE_DIR="$NODE_PREFIX/lib/node_modules/cube"
NODE_SCRIPT="$NODE_PREFIX/lib/node_modules/cube/bin/collector.js"
APP_ARGS="node $NODE_SCRIPT"
USER="cube"
GROUP="cube"

start() {
	log_daemon_msg "Starting $NAME..."
	mkdir -p /var/run/cube
	if start-stop-daemon --background --chdir "$NODE_DIR" --make-pidfile --pidfile $PIDFILE -o --chuid $USER:$GROUP --start --exec "$APP_DIR/$APP_BIN" -- $APP_ARGS ; then
        log_end_msg 0
    else
        log_end_msg 1
    fi
}
 
stop() {
	log_daemon_msg "Stopping $NAME..."
	if start-stop-daemon -o --chuid $USER:$GROUP -K --pidfile $PIDFILE ; then
        log_end_msg 0
    else
        log_end_msg 1
    fi        
}
 
status() {
	PID=$(cat $PIDFILE)
	if ! ps -p $PID > /dev/null 2>&1; then
		echo "$NAME not running."
	else
		echo "$NAME running."
	fi
}
 
case "$1" in
    start)
        start
        ;;

    stop)
        stop
        ;;

    restart|reload|force-reload)
        stop
        sleep 2
        start
        ;;

    status)
        status
        ;;

    *)
        echo "Usage: /etc/init.d/$NAME {start|stop|reload|force-reload|restart|status}"
        exit 2

esac

exit 0
